name: bank-and-deficit staging Deployment to AWS EB Production
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '.git' -x 'node_modules/'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bank-and-deficit-stag
          environment_name: bank-and-deficit-stag-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-028184964655
          version_label: ${{ github.sha }}
          region: ap-south-1
          use_existing_version_if_available: true
          deployment_package: deploy.zip
          wait_for_deployment: true